### ISSUE TITLE
better error handling if invalid or unspecified URL

### ISSUE THREAD

**Issue by ImBobby** [suitmedia/suitcoda#29]
Running both
```Bash
node socmedChecker.js
```
and 
```Bash
node socmedChecker.js --url foobaz
```
return an error

```Bash
/Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/lib/actions.js:133
    if (err) throw err;
                   ^
HeadlessError: Phantom Process died
    at poll_func (/Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:553:10)
    at /Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:45:7
    at ClientRequest.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:475:11)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
    at Function.module.exports.runLoopOnce (/Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/node_modules/deasync/index.js:54:10)
    at Function.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/Suitmedia/suitcoda/socmed/node_modules/node-horseman/node_modules/deasync/index.js:31:19)
```

Node should be exit with status code 1. This also applied to other linters

**Comment by ImBobby** [comment]
ping @setiawanjeje
